apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: gitops-app
        # Image tag is automatically updated by CI pipeline on every push to main
        image: ankacy/gitops-app:a4dc9ad7f797e090c28def683ff3dc8cf988c0c7
        ports:
        - containerPort: 3000