apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: gitops-app
          image: ankacy/gitops-app:041144b43b70a25966566ae9cb99fabf7e33fb7f
          ports:
            - containerPort: 3000
