apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: gitops-app
        # Image tag is automatically updated by CI pipeline on every push to main
        image: ankacy/gitops-app:e3694dd223a8036a15253e52fdda2cb51bbb4e24
        ports:
        - containerPort: 3000